// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: videoStreaming/gunk/v1/videoUpload/all.proto

package videoUpload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoUpload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=Title,json=title,proto3" json:"title,omitempty"`
	VideoFile string `protobuf:"bytes,3,opt,name=VideoFile,json=video_file,proto3" json:"video_file,omitempty"`
	IsActive  bool   `protobuf:"varint,4,opt,name=IsActive,json=is_active,proto3" json:"is_active,omitempty"`
}

func (x *VideoUpload) Reset() {
	*x = VideoUpload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoUpload) ProtoMessage() {}

func (x *VideoUpload) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoUpload.ProtoReflect.Descriptor instead.
func (*VideoUpload) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{0}
}

func (x *VideoUpload) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *VideoUpload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoUpload) GetVideoFile() string {
	if x != nil {
		return x.VideoFile
	}
	return ""
}

func (x *VideoUpload) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateVideoUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoUpload *VideoUpload `protobuf:"bytes,1,opt,name=VideoUpload,json=id,proto3" json:"id,omitempty"`
}

func (x *CreateVideoUploadRequest) Reset() {
	*x = CreateVideoUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoUploadRequest) ProtoMessage() {}

func (x *CreateVideoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoUploadRequest) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVideoUploadRequest) GetVideoUpload() *VideoUpload {
	if x != nil {
		return x.VideoUpload
	}
	return nil
}

type CreateVideoUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"id,omitempty"`
}

func (x *CreateVideoUploadResponse) Reset() {
	*x = CreateVideoUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoUploadResponse) ProtoMessage() {}

func (x *CreateVideoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoUploadResponse) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVideoUploadResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetVideoUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"id,omitempty"`
}

func (x *GetVideoUploadRequest) Reset() {
	*x = GetVideoUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoUploadRequest) ProtoMessage() {}

func (x *GetVideoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoUploadRequest.ProtoReflect.Descriptor instead.
func (*GetVideoUploadRequest) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoUploadRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetVideoUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoUpload *VideoUpload `protobuf:"bytes,1,opt,name=VideoUpload,json=id,proto3" json:"id,omitempty"`
}

func (x *GetVideoUploadResponse) Reset() {
	*x = GetVideoUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoUploadResponse) ProtoMessage() {}

func (x *GetVideoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoUploadResponse.ProtoReflect.Descriptor instead.
func (*GetVideoUploadResponse) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoUploadResponse) GetVideoUpload() *VideoUpload {
	if x != nil {
		return x.VideoUpload
	}
	return nil
}

type UpdateVideoUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoUpload *VideoUpload `protobuf:"bytes,1,opt,name=VideoUpload,json=id,proto3" json:"id,omitempty"`
}

func (x *UpdateVideoUploadRequest) Reset() {
	*x = UpdateVideoUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVideoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoUploadRequest) ProtoMessage() {}

func (x *UpdateVideoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoUploadRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoUploadRequest) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVideoUploadRequest) GetVideoUpload() *VideoUpload {
	if x != nil {
		return x.VideoUpload
	}
	return nil
}

type UpdateVideoUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"id,omitempty"`
}

func (x *UpdateVideoUploadResponse) Reset() {
	*x = UpdateVideoUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVideoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoUploadResponse) ProtoMessage() {}

func (x *UpdateVideoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoUploadResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoUploadResponse) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVideoUploadResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteVideoUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"id,omitempty"`
}

func (x *DeleteVideoUploadRequest) Reset() {
	*x = DeleteVideoUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVideoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoUploadRequest) ProtoMessage() {}

func (x *DeleteVideoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoUploadRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoUploadRequest) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVideoUploadRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteVideoUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVideoUploadResponse) Reset() {
	*x = DeleteVideoUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVideoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoUploadResponse) ProtoMessage() {}

func (x *DeleteVideoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoUploadResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoUploadResponse) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{8}
}

type CompleteVideoUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"id,omitempty"`
}

func (x *CompleteVideoUploadRequest) Reset() {
	*x = CompleteVideoUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteVideoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteVideoUploadRequest) ProtoMessage() {}

func (x *CompleteVideoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteVideoUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteVideoUploadRequest) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteVideoUploadRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type CompleteVideoUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteVideoUploadResponse) Reset() {
	*x = CompleteVideoUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteVideoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteVideoUploadResponse) ProtoMessage() {}

func (x *CompleteVideoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteVideoUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteVideoUploadResponse) Descriptor() ([]byte, []int) {
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP(), []int{10}
}

var File_videoStreaming_gunk_v1_videoUpload_all_proto protoreflect.FileDescriptor

var file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x0b,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00,
	0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x52, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x3a, 0x06, 0x08,
	0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x61, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x02, 0x69, 0x64,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x3f, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x3b, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x06,
	0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x5f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x02, 0x69, 0x64, 0x3a,
	0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x61, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x02,
	0x69, 0x64, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x3f, 0x0a, 0x19, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x3e, 0x0a, 0x18, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x23, 0x0a, 0x19, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00,
	0x22, 0x40, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00,
	0x18, 0x00, 0x22, 0x25, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x32, 0xab, 0x04, 0x0a, 0x15, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x12, 0x25, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x5f, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x22, 0x2e, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x68,
	0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x25, 0x2e,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02,
	0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x68, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x25, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x12, 0x6e, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x27, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x1a, 0x03, 0x88, 0x02, 0x00, 0x42, 0x49, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x2e, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x75,
	0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x3b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x80, 0x01, 0x00,
	0x88, 0x01, 0x00, 0x90, 0x01, 0x00, 0xb8, 0x01, 0x00, 0xd8, 0x01, 0x00, 0xf8, 0x01, 0x01, 0xd0,
	0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescOnce sync.Once
	file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescData = file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDesc
)

func file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescGZIP() []byte {
	file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescOnce.Do(func() {
		file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescData)
	})
	return file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDescData
}

var file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_videoStreaming_gunk_v1_videoUpload_all_proto_goTypes = []interface{}{
	(*VideoUpload)(nil),                 // 0: videoUpload.VideoUpload
	(*CreateVideoUploadRequest)(nil),    // 1: videoUpload.CreateVideoUploadRequest
	(*CreateVideoUploadResponse)(nil),   // 2: videoUpload.CreateVideoUploadResponse
	(*GetVideoUploadRequest)(nil),       // 3: videoUpload.GetVideoUploadRequest
	(*GetVideoUploadResponse)(nil),      // 4: videoUpload.GetVideoUploadResponse
	(*UpdateVideoUploadRequest)(nil),    // 5: videoUpload.UpdateVideoUploadRequest
	(*UpdateVideoUploadResponse)(nil),   // 6: videoUpload.UpdateVideoUploadResponse
	(*DeleteVideoUploadRequest)(nil),    // 7: videoUpload.DeleteVideoUploadRequest
	(*DeleteVideoUploadResponse)(nil),   // 8: videoUpload.DeleteVideoUploadResponse
	(*CompleteVideoUploadRequest)(nil),  // 9: videoUpload.CompleteVideoUploadRequest
	(*CompleteVideoUploadResponse)(nil), // 10: videoUpload.CompleteVideoUploadResponse
}
var file_videoStreaming_gunk_v1_videoUpload_all_proto_depIdxs = []int32{
	0,  // 0: videoUpload.CreateVideoUploadRequest.VideoUpload:type_name -> videoUpload.VideoUpload
	0,  // 1: videoUpload.GetVideoUploadResponse.VideoUpload:type_name -> videoUpload.VideoUpload
	0,  // 2: videoUpload.UpdateVideoUploadRequest.VideoUpload:type_name -> videoUpload.VideoUpload
	1,  // 3: videoUpload.VideoUploadRegService.CreateVideo:input_type -> videoUpload.CreateVideoUploadRequest
	3,  // 4: videoUpload.VideoUploadRegService.GetVideo:input_type -> videoUpload.GetVideoUploadRequest
	5,  // 5: videoUpload.VideoUploadRegService.UpdateVideo:input_type -> videoUpload.UpdateVideoUploadRequest
	7,  // 6: videoUpload.VideoUploadRegService.DeleteVideo:input_type -> videoUpload.DeleteVideoUploadRequest
	9,  // 7: videoUpload.VideoUploadRegService.CompleteVideo:input_type -> videoUpload.CompleteVideoUploadRequest
	2,  // 8: videoUpload.VideoUploadRegService.CreateVideo:output_type -> videoUpload.CreateVideoUploadResponse
	4,  // 9: videoUpload.VideoUploadRegService.GetVideo:output_type -> videoUpload.GetVideoUploadResponse
	6,  // 10: videoUpload.VideoUploadRegService.UpdateVideo:output_type -> videoUpload.UpdateVideoUploadResponse
	8,  // 11: videoUpload.VideoUploadRegService.DeleteVideo:output_type -> videoUpload.DeleteVideoUploadResponse
	10, // 12: videoUpload.VideoUploadRegService.CompleteVideo:output_type -> videoUpload.CompleteVideoUploadResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_videoStreaming_gunk_v1_videoUpload_all_proto_init() }
func file_videoStreaming_gunk_v1_videoUpload_all_proto_init() {
	if File_videoStreaming_gunk_v1_videoUpload_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoUpload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVideoUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVideoUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVideoUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVideoUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVideoUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVideoUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteVideoUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteVideoUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_videoStreaming_gunk_v1_videoUpload_all_proto_goTypes,
		DependencyIndexes: file_videoStreaming_gunk_v1_videoUpload_all_proto_depIdxs,
		MessageInfos:      file_videoStreaming_gunk_v1_videoUpload_all_proto_msgTypes,
	}.Build()
	File_videoStreaming_gunk_v1_videoUpload_all_proto = out.File
	file_videoStreaming_gunk_v1_videoUpload_all_proto_rawDesc = nil
	file_videoStreaming_gunk_v1_videoUpload_all_proto_goTypes = nil
	file_videoStreaming_gunk_v1_videoUpload_all_proto_depIdxs = nil
}
